apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: sandbox
spec:
  ports:
  - name: http
    port: 7111
    protocol: TCP
    targetPort: 3111
    nodePort: 31111
  selector:
    app: techtrends
  sessionAffinity: None
  type: NodePort
